// ── API contract types — request/response shapes for all key routes ──
// Used by both frontend services and server route handlers via `import type`

import type { User, UserProfile, Agent, Conversation, NotificationItem, Memory, Reminder, VoicePreference, LLMPreference } from './models';
export type { User, UserProfile, Agent, Conversation, NotificationItem, Memory, Reminder, VoicePreference, LLMPreference };

// ── Auth ──

export interface AuthRegisterRequest {
  username: string;
  password: string;
  phone?: string;
}

export interface AuthLoginRequest {
  username: string;
  password: string;
}

export interface AuthLoginResponse {
  token: string;
  user: UserProfile;
}

export interface AuthMeResponse {
  user: UserProfile;
}

export interface AuthBootstrapResponse {
  success: boolean;
  user?: UserProfile;
  error?: string;
}

export interface AuthSwitchOrgRequest {
  orgId: string | null;
  orgRole: string | null;
}

export interface AuthSwitchOrgResponse {
  connection: { orgId: string; orgRole: string; orgName: string; connected: boolean } | null;
}

// ── Agents ──

export interface AgentCreateRequest {
  name: string;
  category: string;
  data?: string;
  personalityId?: string;
  modelPreference?: string;
  memoryScope?: 'private' | 'shared';
  autonomyLevel?: 'reactive' | 'semi' | 'full';
  territory?: 'open' | 'sanctuary';
  distilledFrom?: string;
  evidenceMap?: any[];
  relationshipType?: string;
  isFrozen?: boolean;
  seedMemoryIds?: string[];
  executionMode?: string;
}

export interface AgentUpdateRequest {
  name?: string;
  category?: string;
  data?: string;
  personalityId?: string;
  modelPreference?: string;
  memoryScope?: 'private' | 'shared';
  autonomyLevel?: 'reactive' | 'semi' | 'full';
  executionMode?: string;
  skillTags?: string[];
  knowledgeDomains?: string[];
  allowCrossPollination?: boolean;
  isFrozen?: boolean;
  territory?: 'open' | 'sanctuary';
  relationshipType?: string;
  runtimeConfig?: string;
}

export interface AgentListResponse extends Array<Agent> {}

export interface AgentSanctuaryResponse {
  sanctuaries: Array<{
    id: string;
    name: string;
    relationshipType: string;
    isFrozen: boolean;
    memoryCount: number;
    createdAt: string;
    lastActiveAt?: string;
  }>;
}

export interface AgentHistoryMessage {
  role: string;
  content: string;
  createdAt: string;
  mode?: string;
}

// ── Voice ──

export interface VoiceItem {
  voiceId: string;
  name: string;
  provider: string;
  language: string;
  category: 'premade' | 'cloned';
}

export interface VoiceListResponse {
  cloned: VoiceItem[];
  premade: VoiceItem[];
}

export interface VoiceSynthesizeRequest {
  text: string;
  voiceId: string;
  provider: string;
}

export interface VoiceProviderRequest {
  stt?: string;
  tts?: string;
}

export interface VoiceActiveProviderResponse {
  stt: string;
  tts: string;
}

// ── Conversations ──

export interface ConversationListResponse {
  conversations: Conversation[];
}

export interface ConversationMessagesResponse extends Array<{ role: string; content: string; createdAt: string }> {}

export interface ConversationActiveResponse {
  id: string;
  agentId: string;
  status: string;
  messageCount: number;
}

// ── Notifications ──

export interface NotificationListResponse {
  notifications: NotificationItem[];
  unreadCount: number;
}

// ── Settings ──

export interface SettingsKeysResponse {
  [keyName: string]: boolean; // masked — true = configured
}

export interface SettingsKeysRequest {
  keys: Record<string, string>;
}

export interface SettingsSetRequest {
  key: string;
  value: any;
}

// ── System ──

export interface SystemHealthResponse {
  status: 'ok' | 'degraded';
  timestamp: string;
  database: { users: number; agents: number; interactions: number; dirty: boolean };
}

export interface SystemStatsResponse {
  cpu: number;
  ram: { used: number; total: number; percent: number };
  platform: string;
  release: string;
  arch: string;
  hostname: string;
  cpus: number;
  uptime: number;
  gpu: { name?: string; util?: number } | null;
}

export interface LLMProvidersResponse {
  providers: Array<{ id: string; name: string; models: string[]; configured: boolean }>;
}

export interface LLMTestRequest {
  provider: string;
  model: string;
}

export interface LLMTestResponse {
  success: boolean;
  latency?: number;
  error?: string;
}

// ── Skills ──

export interface SkillListResponse {
  skills: Array<{
    name: string;
    description: string;
    enabled: boolean;
    source: string;
    autoGenerated: boolean;
    toolCount: number;
    installedAt: string;
    connected: boolean;
    broken?: boolean;
  }>;
}

// ── Marketplace ──

export interface MarketplaceSkill {
  id: string;
  name: string;
  description: string;
  author: string;
  downloads: number;
  rating: number;
  category: string;
  icon: string;
  installed: boolean;
  version?: string;
  toolCount?: number;
  requiresApiKey?: boolean;
  apiKeyEnv?: string;
  apiKeyUrl?: string;
  requiresSetup?: boolean;
  setupNote?: string;
}

// ── Memory ──

export interface MemoryListResponse {
  memories: Memory[];
}

export interface ReminderListResponse {
  reminders: Reminder[];
}

// ── Preferences ──

export interface PreferencesPetResponse {
  pet?: any;
  accessories?: string[];
}

// ── MCP ──

export interface RemoteDevicesConfig {
  devices: Array<{ name: string; url: string }>;
}
