/**
 * Lumi Skill Generator — LLM-driven MCP server package generation.
 *
 * Takes workflow records (tool call sequences) or natural language descriptions
 * and generates a complete, installable MCP server package in ~/lumi_skills/.
 */
import fs from 'fs';
import path from 'path';
import os from 'os';
import { makeLLMCall, NormalizedMessage } from '../llm/providers';
import { WorkflowRecord, WorkflowStep } from './worklog';
import { mcpManager, SKILLS_DIR } from '../mcp/client';
import { MCPServerConfig } from '../mcp/client';

const SKILLS_DIR_PATH = SKILLS_DIR;

export interface SkillGenerateRequest {
  /** Natural language description of what the skill should do */
  description?: string;
  /** Existing workflows to learn from */
  workflows?: WorkflowRecord[];
  /** LLM provider to use */
  provider?: 'deepseek' | 'qwen' | 'openai' | 'gemini' | 'anthropic';
  model?: string;
  userId?: string;
}

export interface SkillGenerateResult {
  success: boolean;
  skillName?: string;
  toolName?: string;
  directory?: string;
  error?: string;
  generatedCode?: string;
}

const GENERATE_PROMPT = `You are a Skill SDK generator for LumiOS. Your job is to create an MCP (Model Context Protocol) server tool.

## Context
Lumi has learned a repeatable workflow by observing tool execution patterns. You need to encode this knowledge as a standalone MCP tool.

## Input
{inputDescription}

## Output Requirements
Output ONLY a JSON object with these fields:

{
  "skillName": "lowercase-kebab-case-name",
  "toolName": "snake_case_tool_name",
  "toolDescription": "1-2 sentence description of what this tool does",
  "inputSchema": {
    "type": "object",
    "properties": {
      "paramName": { "type": "string", "description": "what this param is" }
    },
    "required": ["paramName"]
  },
  "handlerLogic": "Step-by-step description of what the handler function should do. Be specific about API calls, data transformations, error handling. The handler receives args and returns a string result.",
  "readme": "Markdown documentation: what the skill does, usage example, parameters, output format"
}

## Guidelines
- The skillName should be short and descriptive (max 3 words, kebab-case)
- If the workflow involves web APIs, describe the exact endpoints and parameters
- If using file operations, specify file paths and formats
- handlerLogic should be implementable as a single async TypeScript function
- Keep inputSchema focused: only parameters that change between invocations

JSON output:`;

const SKILL_TEMPLATE = `/**
 * Auto-generated Lumi Skill: {skillName}
 * Generated at: {timestamp}
 * Generator: Lumi Skill SDK
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

// ── Generated Handler ──
{handlerCode}

// ── Schema (generated) ──
const inputSchema = {inputSchema};

// ── MCP Server Entry ──
async function main() {
  const server = new McpServer(
    { name: '{skillName}', version: '1.0.0' },
    { capabilities: { tools: {} } }
  );

  server.registerTool(
    '{toolName}',
    {
      description: '{toolDescription}',
      inputSchema,
    },
    handler
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[Lumi Skill] {skillName} ready');
}

main().catch((err) => {
  console.error('[Lumi Skill] Fatal:', err);
  process.exit(1);
});
`;

const PACKAGE_TEMPLATE = `{
  "name": "lumi-skill-{skillName}",
  "version": "1.0.0",
  "description": "{toolDescription}",
  "type": "module",
  "main": "index.ts",
  "scripts": {
    "start": "npx tsx index.ts"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0",
    "zod": "^3.22.0"
  },
  "lumi": {
    "autoGenerated": true,
    "generatedFrom": "{generatedFrom}",
    "installedAt": "{installedAt}",
    "toolCount": 1
  }
}
`;

/**
 * Generate a skill from workflow records or a natural language description.
 */
export async function generateSkill(
  request: SkillGenerateRequest,
  getDeepSeek: () => any,
  getGemini: () => any,
  getOpenAI?: () => any,
  getAnthropic?: () => any,
  getQwen?: () => any,
): Promise<SkillGenerateResult> {
  // Build input description for LLM
  let inputDescription = '';

  if (request.workflows && request.workflows.length > 0) {
    const intents = [...new Set(request.workflows.map(w => w.userIntent))];
    const allTools = request.workflows.flatMap(w => w.toolSequence);

    inputDescription = `## Observed Workflow Pattern
This workflow has been executed ${request.workflows.length} times.

### User Intent
${intents.join('\n')}

### Tool Call Sequences
${request.workflows.map((w, i) => `
Execution #${i + 1}:
${w.toolSequence.map((s, j) => `  ${j + 1}. ${s.name}(${JSON.stringify(s.args)}) → ${s.resultSummary.slice(0, 100)}`).join('\n')}
`).join('\n')}

### Most Common Tools Used
${topTools(allTools).map(t => `- ${t.name} (${t.count}x)`).join('\n')}
`;
  } else if (request.description) {
    inputDescription = `## User Request\n${request.description}`;
  } else {
    return { success: false, error: 'No workflows or description provided' };
  }

  const prompt = GENERATE_PROMPT.replace('{inputDescription}', inputDescription);

  const messages: NormalizedMessage[] = [
    { role: 'user', content: prompt },
  ];

  const provider = request.provider || 'deepseek';
  const model = request.model || 'deepseek-chat';

  try {
    const response = await makeLLMCall(
      messages,
      [],
      { provider, model, maxTokens: 2048, userId: request.userId || 'skill_gen' },
      getDeepSeek,
      getGemini,
      getOpenAI,
      getAnthropic,
      getQwen,
    );

    const text = response.text || '';
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return { success: false, error: 'LLM did not return valid JSON', generatedCode: text };
    }

    const parsed = JSON.parse(jsonMatch[0]);

    if (!parsed.skillName || !parsed.toolName) {
      return { success: false, error: 'Missing skillName or toolName in generated output', generatedCode: text };
    }

    // Build the skill package
    const skillName = parsed.skillName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const skillDir = path.join(SKILLS_DIR_PATH, skillName);
    const generatedFrom = request.workflows
      ? request.workflows.map(w => w.id).join(',')
      : 'manual';

    const now = new Date().toISOString();

    // Convert handlerLogic into a comment-annotated handler function
    const handlerCode = generateHandlerCode(parsed.handlerLogic, parsed.inputSchema);

    // Build the input schema as a Zod-compatible object literal for the template
    const schemaLiteral = buildSchemaLiteral(parsed.inputSchema);

    // Fill templates
    const indexTs = SKILL_TEMPLATE
      .replace(/{skillName}/g, skillName)
      .replace(/{toolName}/g, parsed.toolName)
      .replace(/{toolDescription}/g, (parsed.toolDescription || parsed.toolName).replace(/"/g, '\\"'))
      .replace(/{timestamp}/g, now)
      .replace('{handlerCode}', handlerCode)
      .replace('{inputSchema}', schemaLiteral);

    const packageJson = PACKAGE_TEMPLATE
      .replace(/{skillName}/g, skillName)
      .replace(/{toolDescription}/g, (parsed.toolDescription || '').replace(/"/g, '\\"'))
      .replace(/{generatedFrom}/g, generatedFrom)
      .replace(/{installedAt}/g, now);

    const readme = (parsed.readme || `# ${skillName}\n\n${parsed.toolDescription}`);

    // Write files
    if (!fs.existsSync(skillDir)) fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, 'package.json'), packageJson);
    fs.writeFileSync(path.join(skillDir, 'index.ts'), indexTs);
    fs.writeFileSync(path.join(skillDir, 'README.md'), readme);

    console.log(`[SkillGen] Generated skill "${skillName}" at ${skillDir}`);

    return {
      success: true,
      skillName,
      toolName: parsed.toolName,
      directory: skillDir,
      generatedCode: indexTs,
    };
  } catch (err: any) {
    console.error('[SkillGen] Generation failed:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Auto-detect repeatable patterns in recent workflows and trigger generation.
 * Returns the generated skill info if a pattern was found and a skill was created.
 */
export async function autoGenerateSkill(
  getDeepSeek: () => any,
  getGemini: () => any,
  getOpenAI?: () => any,
  getAnthropic?: () => any,
  getQwen?: () => any,
): Promise<SkillGenerateResult | null> {
  const { countSimilarWorkflows, getRecentWorkflows, clearWorkflows } = await import('./worklog');

  const all = getRecentWorkflows();
  if (all.length < 3) return null;

  // Group workflows by similar intent (simple keyword overlap)
  const groups: Map<string, WorkflowRecord[]> = new Map();
  const processed = new Set<string>();

  for (const w of all) {
    if (processed.has(w.id)) continue;
    const similar = countSimilarWorkflows(w.userIntent, 3);
    if (similar.length >= 3) {
      const key = w.userIntent.slice(0, 40);
      groups.set(key, similar);
      for (const s of similar) processed.add(s.id);
    }
  }

  for (const [intent, workflows] of groups) {
    console.log(`[SkillGen] Auto-detected pattern: "${intent}" (${workflows.length}x)`);
    const result = await generateSkill(
      { workflows, provider: 'deepseek', model: 'deepseek-chat' },
      getDeepSeek, getGemini, getOpenAI, getAnthropic, getQwen,
    );

    if (result.success && result.skillName) {
      // Install the generated skill
      try {
        mcpManager.installSkill(result.skillName, result.directory!);
        console.log(`[SkillGen] Auto-installed skill "${result.skillName}"`);
        // Clear processed workflows so they don't re-trigger
        for (const w of workflows) {
          const idx = all.indexOf(w);
          if (idx >= 0) all.splice(idx, 1);
        }
      } catch (err: any) {
        console.warn(`[SkillGen] Auto-install failed: ${err.message}`);
      }

      return result;
    }
  }

  return null;
}

// ── Helpers ──

function topTools(steps: WorkflowStep[]): { name: string; count: number }[] {
  const counts: Record<string, number> = {};
  for (const s of steps) {
    counts[s.name] = (counts[s.name] || 0) + 1;
  }
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([name, count]) => ({ name, count }));
}

function generateHandlerCode(handlerLogic: string, inputSchema: any): string {
  const props = inputSchema?.properties || {};
  const paramNames = Object.keys(props);

  const destructure = paramNames.length > 0
    ? `const { ${paramNames.join(', ')} } = args;`
    : '';

  return `/**
 * ${handlerLogic.split('\n').join('\n * ')}
 */
async function handler(args: Record<string, any>): Promise<{ content: Array<{ type: 'text'; text: string }> }> {
  ${destructure}

  // TODO: Implement based on the handler logic above.
  // The logic describes: ${handlerLogic.slice(0, 200)}

  const result = 'Skill executed successfully.';

  return {
    content: [{ type: 'text', text: result }],
  };
}`;
}

function buildSchemaLiteral(schema: any): string {
  if (!schema || !schema.properties) {
    return '{ type: "object", properties: {}, required: [] }';
  }

  const props = schema.properties || {};
  const required = schema.required || [];

  const propEntries = Object.entries(props).map(([key, prop]: [string, any]) => {
    return `  ${key}: z.${mapJsonTypeToZod(prop.type || 'string')}()${prop.description ? `.describe('${prop.description.replace(/'/g, "\\'")}')` : ''}`;
  });

  if (propEntries.length === 0) {
    return `z.object({})`;
  }

  return `z.object({\n${propEntries.join(',\n')}\n})`;
}

function mapJsonTypeToZod(jsonType: string): string {
  switch (jsonType) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return 'array(z.any())';
    case 'object': return 'object({})';
    default: return 'string';
  }
}
