import React, { useState, useEffect, useCallback } from 'react';
import { Sparkles, ShoppingBag, Cpu, Download, Trash2, Power, PowerOff, Plus, RefreshCw, Star, Wrench, CheckCircle, Globe, Calculator, CloudSun, Languages, StickyNote, Timer, Search } from 'lucide-react';
import { GlassCard } from './SharedUI';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { toast } from 'sonner';

interface MarketplaceSkill {
  id: string;
  name: string;
  description: string;
  author: string;
  downloads: number;
  rating: number;
  category: string;
  icon: string;
  installSource?: 'bundled' | 'community';
  installPath?: string;
  installed: boolean;
}

interface InstalledSkill {
  name: string;
  description: string;
  enabled: boolean;
  source: string;
  autoGenerated: boolean;
  toolCount: number;
  installedAt: string;
  connected: boolean;
}

const iconMap: Record<string, React.ReactNode> = {
  CloudSun: <CloudSun size={20} />,
  Languages: <Languages size={20} />,
  Calculator: <Calculator size={20} />,
  StickyNote: <StickyNote size={20} />,
  Timer: <Timer size={20} />,
  Globe: <Globe size={20} />,
  Mail: <MailIcon size={20} />,
};

function MailIcon({ size }: { size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

type Tab = 'marketplace' | 'installed' | 'generate';

export function SkillCenter({ t }: { t: any }) {
  const [activeTab, setActiveTab] = useState<Tab>('marketplace');
  const [marketSkills, setMarketSkills] = useState<MarketplaceSkill[]>([]);
  const [installedSkills, setInstalledSkills] = useState<InstalledSkill[]>([]);
  const [loading, setLoading] = useState(true);
  const [installing, setInstalling] = useState<string | null>(null);

  // Generate state
  const [genDescription, setGenDescription] = useState('');
  const [generating, setGenerating] = useState(false);

  const fetchMarketplace = useCallback(async () => {
    try {
      const res = await fetch('/api/marketplace/skills');
      if (res.ok) setMarketSkills(await res.json());
    } catch {}
  }, []);

  const fetchInstalled = useCallback(async () => {
    try {
      const res = await fetch('/api/skills');
      if (res.ok) {
        const data = await res.json();
        setInstalledSkills(data.skills || []);
      }
    } catch {}
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchMarketplace();
    fetchInstalled();
  }, [fetchMarketplace, fetchInstalled]);

  const handleInstall = async (skill: MarketplaceSkill) => {
    if (skill.installed) return;
    setInstalling(skill.id);
    try {
      const res = await fetch('/api/marketplace/skills/acquire', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          skillId: skill.id,
          skillName: skill.name,
          installSource: skill.installSource,
          installPath: skill.installPath,
        }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success(`"${skill.name}" installed!`);
        fetchInstalled();
      } else {
        toast.error(data.error || 'Install failed');
      }
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      setInstalling(null);
    }
  };

  const handleUninstall = async (name: string) => {
    try {
      const res = await fetch(`/api/skills/${name}`, { method: 'DELETE' });
      if (res.ok) {
        toast.success(`"${name}" uninstalled`);
        fetchInstalled();
        fetchMarketplace();
      }
    } catch (err: any) {
      toast.error(err.message);
    }
  };

  const handleToggle = async (name: string, enabled: boolean) => {
    try {
      const endpoint = enabled ? 'enable' : 'disable';
      await fetch(`/api/skills/${name}/${endpoint}`, { method: 'POST' });
      toast.success(`${enabled ? 'Enabled' : 'Disabled'}: ${name}`);
      fetchInstalled();
    } catch {}
  };

  const handleGenerate = async () => {
    if (!genDescription.trim()) return;
    setGenerating(true);
    try {
      const res = await fetch('/api/skills/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ description: genDescription }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success(`Skill "${data.skillName}" generated!`);
        setGenDescription('');
        fetchInstalled();
      } else {
        toast.error(data.error || 'Generation failed');
      }
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      setGenerating(false);
    }
  };

  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: 'marketplace', label: 'Marketplace', icon: <ShoppingBag size={14} /> },
    { id: 'installed', label: 'Installed', icon: <Cpu size={14} /> },
    { id: 'generate', label: 'Generate', icon: <Sparkles size={14} /> },
  ];

  return (
    <div className="h-full flex flex-col animate-in fade-in slide-in-from-bottom-2 duration-300">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-lg font-bold text-white tracking-tight">Skill Center</h2>
          <p className="text-xs text-white/40 mt-0.5">Browse, install, and manage Lumi's capabilities</p>
        </div>
        <Button
          onClick={() => { fetchMarketplace(); fetchInstalled(); }}
          className="bg-white/5 hover:bg-white/10 border border-white/10 text-xs px-3 py-1.5 rounded-lg"
        >
          <RefreshCw size={12} className="mr-1" /> Refresh
        </Button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 mb-6 bg-white/5 rounded-xl p-1">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 flex items-center justify-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition-all ${
              activeTab === tab.id
                ? 'bg-white/10 text-white shadow-sm'
                : 'text-white/40 hover:text-white/60'
            }`}
          >
            {tab.icon}
            {tab.label}
            {tab.id === 'installed' && (
              <span className="text-[10px] px-1.5 py-0.5 bg-white/10 rounded-full">{installedSkills.length}</span>
            )}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-y-auto custom-scrollbar space-y-3">
        {activeTab === 'marketplace' && (
          <>
            <div className="relative mb-4">
              <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/20" />
              <Input
                placeholder="Search skills..."
                className="w-full pl-9 bg-white/5 border-white/10 rounded-xl py-2 text-sm"
              />
            </div>
            {marketSkills.map(skill => (
              <div key={skill.id} className="p-4 bg-white/5 rounded-2xl border border-white/5 hover:border-white/10 transition-all">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex gap-3">
                    <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center text-white/40 shrink-0">
                      {iconMap[skill.icon] || <Wrench size={20} />}
                    </div>
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <h4 className="font-bold text-white text-sm">{skill.name}</h4>
                        <span className="text-[9px] px-1.5 py-0.5 bg-white/5 rounded-full text-white/30">{skill.category}</span>
                      </div>
                      <p className="text-xs text-white/40 mt-1 line-clamp-2">{skill.description}</p>
                      <div className="flex items-center gap-3 mt-2 text-[10px] text-white/30">
                        <span>{skill.author}</span>
                        <span className="flex items-center gap-1"><Star size={10} className="text-yellow-500" fill="currentColor" />{skill.rating}</span>
                        <span>{skill.downloads.toLocaleString()} installs</span>
                      </div>
                    </div>
                  </div>
                  <Button
                    onClick={() => handleInstall(skill)}
                    disabled={skill.installed || installing === skill.id}
                    className={`shrink-0 text-xs font-bold px-4 py-2 rounded-xl transition-all ${
                      skill.installed
                        ? 'bg-green-500/10 text-green-400 border border-green-500/20'
                        : 'bg-celestial-saturn/10 text-celestial-saturn border border-celestial-saturn/20 hover:bg-celestial-saturn/20'
                    }`}
                  >
                    {skill.installed ? (
                      <><CheckCircle size={12} className="mr-1" /> Installed</>
                    ) : installing === skill.id ? (
                      <><RefreshCw size={12} className="mr-1 animate-spin" /> Installing...</>
                    ) : (
                      <><Download size={12} className="mr-1" /> Install</>
                    )}
                  </Button>
                </div>
              </div>
            ))}
          </>
        )}

        {activeTab === 'installed' && (
          <>
            {loading ? (
              <div className="text-center py-16 text-white/20 text-sm">Loading...</div>
            ) : installedSkills.length === 0 ? (
              <div className="text-center py-16 bg-white/5 rounded-2xl border border-white/5">
                <Wrench size={32} className="text-white/20 mx-auto mb-3" />
                <p className="text-white/30 text-sm font-bold">No skills installed</p>
                <p className="text-white/15 text-xs mt-1">Browse the marketplace or generate one from a description.</p>
              </div>
            ) : (
              installedSkills.map(skill => (
                <div key={skill.name} className="p-4 bg-white/5 rounded-2xl border border-white/5 hover:border-white/10 transition-all">
                  <div className="flex items-start justify-between gap-4">
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h4 className="font-bold text-white text-sm">{skill.name}</h4>
                        {skill.autoGenerated && (
                          <span className="text-[8px] px-1.5 py-0.5 bg-emerald-500/10 text-emerald-400 rounded-full font-bold">Auto</span>
                        )}
                        {skill.connected && (
                          <span className="text-[8px] px-1.5 py-0.5 bg-green-500/10 text-green-400 rounded-full font-bold">Connected</span>
                        )}
                      </div>
                      <p className="text-xs text-white/40 mt-1">{skill.description}</p>
                      <div className="flex items-center gap-3 mt-2 text-[10px] text-white/20">
                        <span>{skill.toolCount} tool{skill.toolCount !== 1 ? 's' : ''}</span>
                        {skill.installedAt && (
                          <span>Installed {new Date(skill.installedAt).toLocaleDateString()}</span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      <button
                        onClick={() => handleToggle(skill.name, !skill.enabled)}
                        className={`p-2 rounded-lg transition-colors ${skill.enabled ? 'text-green-400 hover:bg-green-500/10' : 'text-white/20 hover:bg-white/5'}`}
                      >
                        {skill.enabled ? <Power size={14} /> : <PowerOff size={14} />}
                      </button>
                      <button
                        onClick={() => handleUninstall(skill.name)}
                        className="p-2 hover:bg-red-500/10 rounded-lg text-white/20 hover:text-red-400 transition-colors"
                      >
                        <Trash2 size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </>
        )}

        {activeTab === 'generate' && (
          <div className="p-6 bg-emerald-500/5 rounded-2xl border border-emerald-500/20 space-y-4">
            <div className="flex items-center gap-2">
              <Sparkles size={18} className="text-emerald-400" />
              <h4 className="text-sm font-bold text-emerald-300">Generate a New Skill</h4>
            </div>
            <p className="text-xs text-white/40">
              Describe what the skill should do in plain language. Lumi will generate a complete MCP server package with executable handler code, input schemas, and documentation.
            </p>
            <div className="flex gap-3">
              <Input
                value={genDescription}
                onChange={e => setGenDescription(e.target.value)}
                placeholder="e.g. Generate a weekly report from database data and email it, or fetch stock prices for given tickers..."
                className="flex-1 bg-white/5 border-white/10 rounded-xl py-2 text-sm"
                onKeyDown={e => e.key === 'Enter' && handleGenerate()}
              />
              <Button
                onClick={handleGenerate}
                disabled={generating || !genDescription.trim()}
                className="bg-emerald-500 text-black font-bold text-xs px-6 py-2 rounded-xl hover:scale-105 transition-transform disabled:opacity-40"
              >
                {generating ? 'Generating...' : 'Generate'}
              </Button>
            </div>
            <p className="text-[10px] text-white/20">
              Examples: "Check if a website is down", "Generate a QR code from text", "Convert CSV to JSON", "Fetch Hacker News top stories"
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
